version: 2
updates:
  # Fetch and update latest `nuget` pkgs
  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "daily"
      time: "00:00"
    open-pull-requests-limit: 10
    commit-message:
      prefix: "chore"
      include: "scope"

  # Fetch and update latest `github-actions` pkgs
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      time: "00:00"
    labels:
      - "skip-changelog"
    open-pull-requests-limit: 10
    commit-message:
      prefix: "ci"
      include: "scope"

