---
name: "Keycloak Authentication"
guid: "40886866-b3dd-4d6a-bf9b-25c83e6c3d10"
version: "1.0.0.0"
targetAbi: "10.7.0.0"
framework: "net5.0"
overview: "Authenticate users against Keycloak"
description: >
  Authenticate users against Keycloak.
category: "Authentication"
owner: "Ugrend"
artifacts:
- "Jellyfin.Plugin.Keycloak.dll"
- "JWT.dll"
changelog: >
  changelog
